name: louredmond
favicon: null
layout_spectrum: 1
typography_spectrum: 0.43045
title: Inspire Transformation
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#d9d6e6'
    - '#8d7f68'
    - '#584a36'
    - '#1d1814'
    - '#c7bdb7'
  brandStrength: 0.4375
  lightness: 0.25
  saturation: 0.3125
  rhythmicContrast: 0.25
purpose:
  - name: engagement
    item: null
    url: null
