name: louredmond
favicon: null
layout_spectrum: 1
typography_spectrum: 0.43045
title: Inspire Transformation
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E7D9AB'
    - '#887765'
    - '#5D5353'
    - '#302838'
  brandStrength: 0.8125
  lightness: 0.375
  saturation: 0.3125
  rhythmicContrast: 0.5
purpose:
  - name: engagement
    url: null
    item: null
