name: louredmond
favicon: null
layout_spectrum: 1
typography_spectrum: 0.43045
title: Inspire Transformation
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#fdfdfe'
    - '#dc0000'
    - '#584950'
    - '#6a7b95'
  brandStrength: 0.8125
  lightness: 0.75
  saturation: 0.5
  rhythmicContrast: 0.75
purpose:
  - name: engagement
    item: null
    url: null
