name: louredmond
favicon: null
layout_spectrum: 1
typography_spectrum: 0.43045
title: Inspire Transformation
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#4f7cc7'
    - '#464644'
    - '#f1fdf9'
    - '#191f05'
    - '#aa8f5f'
  brandStrength: 0.875
  lightness: 1
  saturation: 1
  rhythmicContrast: 0.25
purpose:
  - name: engagement
    item: null
    url: null
